### ISSUE TITLE
Consider replacing victoria with timescaledb

### ISSUE THREAD

**Issue by banteg** [yearn/yearn-exporter#208]
as per @mariuspod idea, we could avoid duplicating the data and store everything in postgres, getting the best of both worlds

we could even keep the grafana dashboard code intact by using [promscale](https://docs.timescale.com/promscale/latest/about-promscale/), which would translate the promql queries
![](https://s3.amazonaws.com/assets.timescale.com/docs/images/promscale-arch.png)

**Comment by 0xkofee** [comment]
I'm trying to make sense on how to stand a poc up in this project

**Comment by 0xkofee** [comment]
### Summary
Switching over seems trivial but there are some issues outlined below. To get setup, we need timescale running with the promscale extension installed. The image I selected already has that. We also need promscale itself which is just a layer above timescale that provides the prometheus read/write apis. Think of promscale as a microservice that sits on top of timescaledb.

## WIP
https://github.com/yearn/yearn-exporter/pull/337

## Issues
Grafana auto selects/calculates intervals based off of [this formula](https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__interval). Once the interval is calculated, it sends it as part of the read api request. The yearn exporter unfortunately only [supports/saves intervals for: 15s, 30s, 1m, 5m, 15m, 30m, 1h, 1d](https://github.com/yearn/yearn-exporter/blob/master/yearn/historical_helper.py#L74).

Because of that, when grafana auto calculates an interval and requests data for that interval, timescaledb returns no data for any interval we never persisted data for. [Victoriadb doesn't have this problem](https://docs.victoriametrics.com/keyConcepts.html?highlight=interval#query-data) because when data for an interval is requested, it will find the nearest data point if the requested data point is missing. Therefore, all interval requests are supported.

The only solutions that I thought of is to add more intervals to the `historical_helper.py` file. This will save more intervals to timescale which will allow support for more time range drop downs. For example when a time range of 90d was selected, grafana requests 12h intervals. We would need to add a 12h interval to `historical_helper.py`. This will make the exporter run longer however. I've been asking around to see if we can pre-define the intervals grafana auto selects but I haven't found anything so far.

**Comment by DarkGhost7** [comment]
Closing for now as the historical rebuild showed multiple issues with the promscale <-> timescale integration which deleted datapoints after insertion under certain conditions:

ERROR:  duplicate key value violates unique constraint \"_hyper_627_195351_chunk_data_series_id_time_308

Also promscale has been officially discontinued: https://docs.timescale.com/promscale/latest/
